@startuml
start
:User executes sort budget by name command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([is valid command])
    :Sort all budgets in NUSave in alphabetical order;
    :Display sorted list of budgets in NUSave;
else ([else])
:Display invalid command result to the user;
endif
stop
@enduml