@startuml
skinparam Sequence {
    MessageAlign center
}
box "Logic" #LightBlue
participant ":LogicManager" as LM
participant ":MainPageParser" as MPP
participant ":FindBudgetCommandParser" as FBCP
participant "command:FindBudgetCommand" as FBC
participant "result:CommandResult" as CR
end box

box "Model" #LightYellow
participant "m:Model" as M
end box

[-> LM : execute("find NUS")
activate LM
LM -> MPP : execute("find NUS")
activate MPP

create FBCP
MPP -> FBCP
activate FBCP
MPP <-- FBCP
deactivate FBCP

MPP -> FBCP : parse("NUS")
activate FBCP

create FBC
FBCP -> FBC
activate FBC
FBCP <-- FBC : command
deactivate FBC
MPP <-- FBCP : command
deactivate FBCP
LM <-- MPP : command
deactivate MPP
LM -> FBC : execute(m)
activate FBC

FBC -> M : findBudget("NUS")
activate M
FBC <-- M
deactivate M

create CR
FBC -> CR
activate CR
FBC <-- CR : result
deactivate CR

LM <-- FBC : result
deactivate FBC
[<-- LM : result
deactivate LM
@enduml
