@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyNusave <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Interface Renderable <<Interface>>
Class Nusave
Class ReadOnlyNusave
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Budget {
Class Budget
Class Threshold
Class Expenditure
Class "Name" as budgetName
Class "Date" as budgetDate
Class BudgetList
}

Package Expenditure {
Class ExpenditureList
Class Expenditure
Class "Name" as expenditureName
Class Price
Class "Date" as expenditureDate
}

Package Tag {
Class Tag
}
}

Package State {
class StateManager
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Nusave .up.|> ReadOnlyNusave
Nusave -right-> Renderable : ObservableList

Model .right.> ObservableList

ModelManager -right-> StateManager
ModelManager .up.|> Model
ModelManager *--> "1" Nusave
ModelManager *-left-> "1" UserPrefs
ModelManager --> Renderable : FilteredList

UserPrefs .up.|> ReadOnlyUserPrefs

Nusave *--> "1" BudgetList
BudgetList "1" o--> "*" Budget
Budget .up.|> Renderable
Budget *--> budgetName
Budget *--> budgetDate
Budget "1" *--> "1" ExpenditureList
Budget *--> Threshold : "Optional"

ExpenditureList --> "*" Expenditure

Expenditure .up.|> Renderable
Expenditure *-down-> expenditureName
Expenditure *-down-> Price
Expenditure *-down-> expenditureDate
Expenditure *--> "*" Tag
expenditureDate -[hidden]right-> Threshold
Threshold -[hidden]right-> Expenditure

@enduml
