@startuml
skinparam Sequence {
    MessageAlign center
}
box Logic #LightBlue
participant ":MainPageParser" as MainPageParser
participant ":DeleteBudgetCommandParser" as DeleteBudgetCommandParser
participant "d:DeleteBudgetCommand" as DeleteBudgetCommand
end box

[-> MainPageParser : parseCommand("delete 1")
activate MainPageParser
create DeleteBudgetCommandParser
MainPageParser -> DeleteBudgetCommandParser : parse("1")
activate DeleteBudgetCommandParser
create DeleteBudgetCommand
DeleteBudgetCommandParser -> DeleteBudgetCommand
activate DeleteBudgetCommand
DeleteBudgetCommand --> DeleteBudgetCommandParser : d
DeleteBudgetCommandParser --> MainPageParser : d
deactivate DeleteBudgetCommandParser
DeleteBudgetCommandParser -[hidden]-> MainPageParser
destroy DeleteBudgetCommandParser
[<-- MainPageParser : d
deactivate MainPageParser
[<-[hidden]- MainPageParser
destroy MainPageParser
@enduml
