@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":MainPageParser" as MainPageParser LOGIC_COLOR
participant ":DeleteBudgetCommandParser" as DeleteBudgetCommandParser LOGIC_COLOR
participant "d:DeleteBudgetCommand" as DeleteBudgetCommand LOGIC_COLOR
end box

[-> MainPageParser : parseCommand("delete 1")
activate MainPageParser
create DeleteBudgetCommandParser
MainPageParser -> DeleteBudgetCommandParser : parse("1")
activate DeleteBudgetCommandParser
create DeleteBudgetCommand
DeleteBudgetCommandParser -> DeleteBudgetCommand
activate DeleteBudgetCommand
DeleteBudgetCommand --> DeleteBudgetCommandParser : d
DeleteBudgetCommandParser --> MainPageParser : d
deactivate DeleteBudgetCommandParser
DeleteBudgetCommandParser -[hidden]-> MainPageParser
destroy DeleteBudgetCommandParser
[<-- MainPageParser : d
deactivate MainPageParser
[<-[hidden]- MainPageParser
destroy MainPageParser
@enduml
