@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage {
Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface NusaveStorage <<Interface>>
Class StorageManager
Class JsonUserPrefsStorage
Class JsonNusaveStorage
Class JsonSerializableNusave
}

StorageManager .left.|> Storage
StorageManager -right-> UserPrefsStorage
StorageManager --> NusaveStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonNusaveStorage .left.|> NusaveStorage
JsonNusaveStorage .down.> JsonSerializableNusave
@enduml
