@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface NusaveStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonNusaveStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> NusaveStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonNusaveStorage .left.|> NusaveStorage
JsonNusaveStorage .down.> JsonSerializableNusave
JsonSerializableNusave -right-> "*" JsonAdaptedBudget
JsonAdaptedBudget -right-> "*" JsonAdaptedExpenditure
JsonAdaptedExpenditure -right-> "*" JsonAdaptedTag
@enduml
