@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>> {
Interface Ui <<Interface>>
Interface StateBinder <<Interface>> {
+ void bind()
}

Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class StateBinderList

Class CommandBox
Class Title
Class ResultDisplay
Class InfoBox
Class HelpWindow
Class RenderableListPanel
Class BudgetCard
Class ExpenditureCard
Class InfoBoxStateBinder
Class TitleStateBinder
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow

RenderableListPanel -down-> BudgetCard
RenderableListPanel -down-> ExpenditureCard

MainWindow -left-|> UiPart
MainWindow *--> ResultDisplay
MainWindow *--> CommandBox
MainWindow *--> Title
MainWindow *--> InfoBox
MainWindow *-right-> RenderableListPanel
MainWindow *--> HelpWindow
MainWindow -right-> StateBinderList

StateBinderList -down-> StateBinder

InfoBoxStateBinder .up.> StateBinder
TitleStateBinder .up.> StateBinder

BudgetCard -right-> Model
ExpenditureCard -right-> Model

CommandBox -down-|> UiPart
Title -down-|> UiPart
ResultDisplay -down-|> UiPart
InfoBox -down-|> UiPart
RenderableListPanel -down-|> UiPart
BudgetCard -down-|> UiPart
ExpenditureCard -down-|> UiPart
HelpWindow -down-|> UiPart

UiManager -up-> Logic
MainWindow -up-> Logic

@enduml
