@startuml
skinparam Sequence {
    MessageAlign center
}
box Logic #LightBlue
participant ":LogicManager" as LogicManager
participant ":MainPageParser" as MainPageParser
participant "c:UndoCommand" as UndoCommand
participant "result:CommandResult" as CommandResult
end box

box Model #LightYellow
participant "m:ModelManager" as Model
participant ":HistoryManager<VersionedNusave>" as HistoryManager
end box
[-> LogicManager : execute("undo")
activate LogicManager

create MainPageParser
LogicManager -> MainPageParser
activate MainPageParser
deactivate MainPageParser
MainPageParser --> LogicManager
deactivate MainPageParser

LogicManager -> MainPageParser : parseCommand("undo")
activate MainPageParser

create UndoCommand
MainPageParser -> UndoCommand
activate UndoCommand

UndoCommand --> MainPageParser : c
deactivate UndoCommand

MainPageParser --> LogicManager : c
deactivate MainPageParser
MainPageParser -[hidden]-> LogicManager
destroy MainPageParser

LogicManager -> UndoCommand : execute(m)
activate UndoCommand

UndoCommand -> Model : undo()
activate Model

Model -> HistoryManager : getHistory()
activate HistoryManager

HistoryManager --> Model : h
deactivate HistoryManager


Model -> Model : loadVersionedNusave(h)
activate Model
Model --> Model
deactivate Model

Model --> UndoCommand
deactivate Model

create CommandResult
UndoCommand -> CommandResult
activate CommandResult
CommandResult --> UndoCommand : result
deactivate CommandResult

UndoCommand --> LogicManager : result
deactivate UndoCommand

[<--LogicManager : result
deactivate LogicManager

hide footbox
@enduml
