@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After "undo"

package HistoryManager {
    class State1 as "__vn1:Node<VersionedNusave>__"
    class State2 as "__vn2:Node<VersionedNusave>__"
    class State3 as "__empty:Node<VersionedNusave>__"
    class State4 as "__empty:Node<VersionedNusave>__"
}
State1 -right-> State2
State2 -left-> State1
State2 -right-> State3
State3 -left-> State2
State3 -[hidden]right-> State4
hide State4

class Pointer as "Current Pointer" #FFFFF
Pointer -up-> State1
@end
