@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial State

package HistoryManager {
    class State1 as "__empty:Node<VersionedNusave>__"
    class State2 as "__empty:Node<VersionedNusave>__"
    class State3 as "__empty:Node<VersionedNusave>__"
    class State4 as "__empty:Node<VersionedNusave>__"
}
State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
State3 -[hidden]right-> State4
hide State2
hide State3
hide State4

class Pointer as "Current Pointer" #FFFFF
Pointer -up-> State1
@end
