@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After "create n/demo2"

package HistoryManager {
    class State1 as "__vn1:Node<VersionedNusave>__"
    class State2 as "__vn2:Node<VersionedNusave>__"
    class State3 as "__vn3:Node<VersionedNusave>__"
    class State4 as "__empty:Node<VersionedNusave>__"
}
State1 -right-> State2
State2 -left-> State1
State2 -right-> State3
State3 -left-> State2
State3 -right-> State4
State4 -left-> State3

class Pointer as "Current Pointer" #FFFFF
Pointer -up-> State4
@end
