@startuml
skinparam Sequence {
    MessageAlign center
}
box Logic #LightBlue
participant ":LogicManager" as LogicManager
participant ":MainPageParser" as MainPageParser
participant "u:UndoCommand" as UndoCommand
end box

box Model #LightYellow
participant ":Model" as Model
participant ":HistoryManager<VersionedNusave>" as HistoryManager
end box
[-> LogicManager : execute(undo)
activate LogicManager

create MainPageParser
LogicManager -> MainPageParser
activate MainPageParser
deactivate MainPageParser
MainPageParser --> LogicManager
deactivate MainPageParser

LogicManager -> MainPageParser : parseCommand(undo)
activate MainPageParser

create UndoCommand
MainPageParser -> UndoCommand
activate UndoCommand

UndoCommand --> MainPageParser : u
deactivate UndoCommand

MainPageParser --> LogicManager : u
deactivate MainPageParser
MainPageParser -[hidden]-> LogicManager
destroy MainPageParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undo()
activate Model

Model -> HistoryManager : getHistory()
activate HistoryManager

HistoryManager --> Model : h:VersionedNusave
deactivate HistoryManager


Model -> Model : loadVersionedNusave(h)
activate Model
Model --> Model
deactivate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager : result
deactivate LogicManager

hide footbox
@enduml
