@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After "create n/demo"

package HistoryManager {
    class State1 as "__vn0:Node<VersionedNusave>__"
    class State2 as "__empty:Node<VersionedNusave>__"
    class State3 as "__empty:Node<VersionedNusave>__"
    class State4 as "__empty:Node<VersionedNusave>__"
}
State1 -right-> State2
State2 -left-> State1
State2 -[hidden]right-> State3
State3 -[hidden]right-> State4
hide State3
hide State4

class Pointer as "Current Pointer" #FFFFF
Pointer -up-> State2
@end
